import pkg from 'hardhat';
const { ethers } = pkg;
import fs from "fs/promises";
import path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying RockBottomFactory with account:", deployer.address);
  console.log("Account balance:", (await ethers.provider.getBalance(deployer.address)).toString());

  const Factory = await ethers.getContractFactory("RockBottomFactory");
  const factory = await Factory.deploy();
  await factory.waitForDeployment();

  const factoryAddress = await factory.getAddress();
  console.log("RockBottomFactory deployed to:", factoryAddress);

  // Read ABI
  const artifactsDir = path.resolve("./artifacts/contracts");
  
  const factoryArtifact = JSON.parse(
    await fs.readFile(path.join(artifactsDir, "RockBottomFactory.sol", "RockBottomFactory.json"), "utf8")
  );
  const poolArtifact = JSON.parse(
    await fs.readFile(path.join(artifactsDir, "MilestonePool.sol", "MilestonePool.json"), "utf8")
  );
  
  // Save ABI to frontend
  const frontendContractsPath = path.resolve("./src/utils/contracts.js");
  const content = `
// Auto-generated by deploy-factory.js
export const FACTORY_ADDRESS = "${factoryAddress}";

export const FACTORY_ABI = ${JSON.stringify(factoryArtifact.abi, null, 2)};
export const POOL_ABI = ${JSON.stringify(poolArtifact.abi, null, 2)};
`;

  await fs.writeFile(frontendContractsPath, content);
  console.log("Saved ABIs to src/utils/contracts.js");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
